### ISSUE TITLE
Website Usability issue.

### ISSUE THREAD

**Issue by tgeorgeux** [BramvdnHeuvel/dnd5e-town-generator#1]
Hey man, great content. I don't know if there's a different repo for a pages link for this tool, but I couldn't' find one so I'm putting it here.

When you generate a town and it lists the adventures that live there, the clickable div goes out all the way across the page. So if you're a serial white-space clicker like me, you will end up clicking links on accident all the time. Mabye limit those divs with a ```max-width``` ? I can take a crack at opening a PR if that helps.

**Comment by BramvdnHeuvel** [comment]
Whoops, you're right! It seems like I've messed up the order of the paragraph and anchor tags. I'll fix that as soon as possible!

**Comment by BramvdnHeuvel** [comment]
This issue has been resolved with commit https://github.com/BramvdnHeuvel/dnd5e-town-generator/commit/4bd6d7c43a6f11179a580a31e7e42359d5a9b1cf! I'm closing the issue now.
